# HEX в таком стиле: #FFFFF или §x§E§9§6§B§6§B

settings:
  item-text: "&c❌ &f%time% &7(%amount%)" # Текст над предметом, который будет очищен
  time-clear-item: 120 # Сколько времени будет лежать предмет, перед тем, как очиститься. Указывать в секундах
  world-blacklist: # Миры, в которых не будет работать очистка
    - "blacklist-world" # Названия миров, может быть просто пустым название, если функция вам не нужна
  hologram-after-time: # Настройка, чтобы голограмма не сразу показывала время, а после определённого время после выброса
    enable: false # Включить ли функцию
    holo-activation-time: 60 # После какой секунды появляется голограмма


messages:
  on-clear-message: "&aВы очистили всё с пола!"
  usage-message: "&fУкажите что вы хотите сделать: &a/hic clear"
  no-permission: "&cНет прав на данную команду!"
  config-reload-message: "&aВы перезагрузили конфиг!"

particle-settings:
  use-particle-on-clear: true # Использовать ли партиклы при очистке предмета
  particle-type: "CRIT" # Тип партикла при исчезновении предмета
  particle-count: 10 # Кол-во партиклов


sound-settings:
  use-sound-on-clear: true # Использовать ли звук при очистке предмета
  radius: 7 # Радиус в блоках от предмета, чтобы услышать звук
  sound-name-on-clear: "ENTITY_ITEM_BREAK" # Название звука, можно найти по запросу: "звуки майнкрафт spigot"
  volume-on-clear: 0.3 # Громкость звука
  pitch-on-clear: 1.0 # Высота звука

items-settings:
  DIAMOND_BLOCK: # Материя предмета которого нужно проверять
    start-clear-item: 25 # Указывать в секундах
